#!/bin/sh

~/.config/bspwm/autostart.sh &

bspc monitor HDMI-A-0 -d          I II III
bspc monitor DisplayPort-0 -d     IV V VI

bspc config border_width          3
bspc config window_gap            5

bspc config automatic_scheme      spiral
bspc config initial_polarity      first_child
bspc config split_ratio           0.51

bspc config active_border_color   '#343434'
bspc config focused_border_color  '#f9f9f9'
bspc config normal_border_color   '#000000'

bspc rule -a Zathura state=tiled
bspc rule -a Xdg-desktop-portal-gtk focus=on state=tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on focus=on manage=off
