#!/bin/sh

~/.config/bspwm/autostart.sh &

bspc monitor HDMI-A-0 -d          1 2 3
bspc monitor DisplayPort-0 -d     8 9 0

bspc config border_width          2
bspc config window_gap            0

bspc config automatic_scheme      spiral
bspc config initial_polarity      first_child
bspc config split_ratio           0.53

bspc config active_border_color   '#343434'
bspc config focused_border_color  '#f9f9f9'
bspc config normal_border_color   '#000000'

bspc rule -a Zathura state=tiled
bspc rule -a '*:*:Save File' state=tiled focus=on
bspc rule -a '*:*:Open Files' state=tiled focus=on
bspc rule -a float-term state=floating focus=on
bspc rule -a scrcpy state=floating focus=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on focus=on manage=off
